# Funding configuration

# github: [maintainer]
# patreon: projectname
# open_collective: projectname
# ko_fi: maintainer
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: maintainer
# issuehunt: maintainer
# custom: ['https://yourwebsite.com/donate', 'https://another-link.com']

