/**
 * Game configuration constants
 */

export const GAME_CONFIG = {
  // Canvas
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  CANVAS_BG_COLOR: '#1a1a2e',

  // Player
  PLAYER_WIDTH: 40,
  PLAYER_HEIGHT: 40,
  PLAYER_SPEED: 5,
  PLAYER_JUMP_FORCE: 12,
  PLAYER_COLOR: '#00ff00',

  // Physics
  GRAVITY: 0.5,
  FRICTION: 0.9,
  MAX_FALL_SPEED: 15,

  // Obstacles
  OBSTACLE_SPAWN_INTERVAL: 2000,
  OBSTACLE_MIN_WIDTH: 30,
  OBSTACLE_MAX_WIDTH: 80,
  OBSTACLE_MIN_HEIGHT: 40,
  OBSTACLE_MAX_HEIGHT: 100,
  OBSTACLE_SPEED: 3,
  OBSTACLE_COLOR: '#ff4444',

  // Power-ups
  POWERUP_SPAWN_INTERVAL: 5000,
  POWERUP_SIZE: 30,
  POWERUP_DURATION: 5000,

  // Scoring
  SCORE_PER_OBSTACLE: 10,
  COMBO_MULTIPLIER: 0.2,
  TIME_BONUS_MULTIPLIER: 1,

  // Difficulty
  DIFFICULTY_INCREASE_INTERVAL: 30000,
  DIFFICULTY_MULTIPLIER: 0.1,
  MAX_DIFFICULTY: 3,

  // Audio
  MASTER_VOLUME: 1,
  SFX_VOLUME: 0.7,
  MUSIC_VOLUME: 0.5,

  // UI
  HUD_PADDING: 20,
  MINIMAP_WIDTH: 150,
  MINIMAP_HEIGHT: 100,

  // Performance
  TARGET_FPS: 60,
  MAX_PARTICLES: 1000,
} as const
